@startuml
title 基于GitHub的实验管理平台-选择课程用例的顺序图
actor 教师
教师 ->系统:成功登陆该系统
教师-> 课程: 查询课程
课程-->教师: 显示需要教授的课程
教师->课程 :选择课程
系统-->教师:提示选择的结果

actor 学生
学生->系统:成功登陆该系统
系统->课程:查询课程
课程 -->学生:显示所有可选择的课程
学生->课程:选择课程
系统->学生:提示选课成功与否
@enduml